- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
- name: Copy Nginx configuration
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx
- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes