repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.2
    hooks:
      - id: ansible-lint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['--strict']

  - repo: https://github.com/prettier/prettier
    rev: 2.6.0
    hooks:
      - id: prettier
        files: '\.(yaml|yml|j2)$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
